// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import * as THREE from "three";
// import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";
// import { GLTF } from "three-stdlib";

// type GLTFResult = GLTF & {
//   nodes: {
//     mesh_0: THREE.Mesh;
//   };
//   materials: {};
// };

// export function Model(props: JSX.IntrinsicElements["group"]) {
//   const { nodes, materials } = useGLTF(
//     "/Models/uploads_files_6203010_Futuristic+Combat+Robot+Soldier+(1).glb"
//   ) as GLTFResult;
//   return (
//     <group {...props} dispose={null} scale={2.8} position={[0, 0.2, 0]}>
//       <group>
//         <mesh
//           name="mesh_0"
//           castShadow
//           receiveShadow
//           geometry={nodes.mesh_0.geometry}
//           material={nodes.mesh_0.material}
//         />
//       </group>
//     </group>
//   );
// }

// useGLTF.preload(
//   "/uploads_files_6203010_Futuristic+Combat+Robot+Soldier+(1).glb"
// );

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Updated for Old Ferris Wheel model with internal animations
*/

import * as THREE from "three";
import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: Record<string, THREE.Mesh>;
  materials: Record<string, THREE.Material>;
  animations: THREE.AnimationClip[];
};

export function Model(props: React.ComponentProps<'group'>) {
  const group = useRef<THREE.Group>(null!);
  const { scene, animations } = useGLTF(
    "/Models/old_ferris_wheel.glb"
  ) as unknown as GLTFResult;

  // Use the animations from the model
  const { actions } = useAnimations(animations, group);
  
  // Base position that you can easily change
  const basePosition: [number, number, number] = [0, -2, 0];
  const baseScale = 0.09;

  // Play all internal animations
  useEffect(() => {
    // Enable shadows
    scene.traverse((child) => {
      if ((child as THREE.Mesh).isMesh) {
        const mesh = child as THREE.Mesh;
        mesh.castShadow = true;
        mesh.receiveShadow = true;
      }
    });

    // Play all available animations
    if (actions) {
      Object.values(actions).forEach((action) => {
        if (action) {
          action.play();
        }
      });
    }
  }, [scene, actions]);

  // Optional: Add gentle floating motion to the entire ferris wheel
  useFrame(({ clock }) => {
    const t = clock.getElapsedTime();
    if (group.current) {
      // Very subtle vertical motion
      group.current.position.y = basePosition[1] + Math.sin(t * 0.3) * 0.05;
      group.current.position.x = basePosition[0];
      group.current.position.z = basePosition[2];
    }
  });

  return (
    <group ref={group} {...props} dispose={null} scale={baseScale} position={basePosition} rotation={[0, 0, 0]}>
      <primitive object={scene} />
    </group>
  );
}

useGLTF.preload("/Models/old_ferris_wheel.glb");